### PR TITLE
fix(html): ensure valid table structure

### LINKED ISSUE #27: patch() can be used to strangely append table cells to a table
## Expected Behavior

Generally, I would expect an error it attempting to append invalid children, or perhaps for the action to be ignored (want a warning to be emitted). If the method is going to gracefully reconcile the tree, it needs to adhere to DOM specification and ensure that children are attached to allowed parent nodes. A table cell must be attached to a table row.

## Current Behavior

The `patch` method attempts to gracefully handle the case where a table cell (`td` or `th`) is appended directly to a `table` element. If the cell is a `td`, the library attempts to find the last available `tbody` and append the node. If there is no available `tbody`, one is created and added to the table. However, there is no `tr` added. If the cell is a `th`, the existing logic is to create a `thead` to append the node, again without a parent row. However, unlike the `td`, it does not look for an existing `thead` and always create a new header element! But a table can only ever have a single `thead`!

## Possible Solution

I'm not sure of the best possible solution, but this existing logic could at least be greatly improved:
- table cells should always be wrapped in a `tr`. So, adding a `thead` or `tbody` is not enough. There also must be a `tr` included in the logic.
   - attempt to append a `td` to the last `tr` in the last `tbody`
   - if neither exists, create both a `tbody` and `tr` and append the node
   - if either exists, create the other and correct the tree before attaching the node
- when adding a `th` to a `thead`, first see if there is an existing `thead`

## Steps to Reproduce (for bugs)

Here's one example showing the issue w/ the `th`
```js
const jsonml = require('@condenast/jsonml');
const { jsdom } = require('jsdom'); // using jsdom@8.4 matching this library (for now)

const document = jsdom();
const elem = document.createElement('table'); // empty table

jsonml.patch(elem, ['', ['th', 'A']);
console.log(elem.outerHTML);
// <table><thead><th>A</th></thead></table>

jsonml.patch(elem, ['', ['th', 'B']);
console.log(elem.outerHTML);
// <table><thead><th>A</th></thead><thead><th>B</th></thead></table>
```

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

### PR DESCRIPTION
**Pull request by pgoldrbx**
## Description

- Ensure table cells are always appended to rows
- Append `th` cells to existing an existing `thead`
- Append `td` cells the last row in the last `tbody`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore, documentation, cleanup

## Related Issue

Fixes #27

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: lib/html.js [hunk 1]
```diff
@@ -490,15 +490,31 @@ var appendDOM = function(elem, child) {
...
+        if (!section) {
+          section = createElement(isHeader ? 'thead' : 'tbody');
+          elem.appendChild(section);
+        }
+        if (childTag === 'tr') {
+          section.appendChild(child);
+        } else {
+          // find last tr
+          var tr;
+          for (var i = section.childNodes.length - 1; i >= 0 && !tr; i--) {
```
Comment (neilius) [inline lib/html.js]: The comment says find the last one, but wouldn't you want to break out of the loop once you have a value for `tr` here since it's iterating backwards? Or am I missing something?

Comment (natemcdowel) [inline lib/html.js]: Some of this nested logic would be more readable if it were wrapped in a method.

Comment (pgoldrbx) [reply lib/html.js]: `i >= 0 && !tr`

I could explicitly `break` if that's easier to read. (probably)

Comment (pgoldrbx) [reply lib/html.js]: I agree. I was avoiding any sort of refactoring but maybe I ought to?

Comment (neilius) [reply lib/html.js]: I am missing something! `&& !tr` is sneaky in there

Comment (pgoldrbx) [reply lib/html.js]: i'll change this to be less sneaky :)

Comment (neilius) [reply lib/html.js]: Heh, saw it right as you commented... yeah, I think it'd be a bit easier to read if it were more explicit. My mind scans over the line entirely when I see a `for` and just assumes it's straight iteration over elements but that could just be me 🤷‍♂

File: lib/html.js [hunk 2]
```diff
@@ -490,15 +490,32 @@ var appendDOM = function(elem, child) {
...
+        }
+        if (childTag === 'tr') {
+          section.appendChild(child);
+        } else {
+          // find last tr
+          var tr;
+          for (var i = section.childNodes.length - 1; i >= 0; i--) {
+            if (section.childNodes[i].tagName.toLowerCase() === 'tr') {
+              tr = section.childNodes[i];
+              break;
```
Comment (pgoldrbx) [inline lib/html.js]: @neilius nice and clear now
